# Change these first
owner: brockbreacher # Your GitHub organization or username, where this repository lives
repo: statuspage # The name of this repository

sites:
  - name: Retriox
    url: https://retriox.net
  - name: Retriox Forums
    url: https://forums.retriox.net
  - name: Join-Bot
    url: http://game.brbr.xyz:25569/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.retriox.net
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Retriox Upptime
  introTitle: ""
  introMessage: 
  navbar:
    - title: Status
      href: /
    - title: Retriox
      href: https://retriox.net

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
